### ISSUE TITLE
Error when trying to open a .raw file

### ISSUE THREAD

**Issue by SquidingTin** [0xC0000054/pdn-cameraraw#2]
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at RawFileTypePlugin.EndianBinaryReader.FillBuffer(Int32 minBytes)
   at RawFileTypePlugin.EndianBinaryReader.ReadUInt16()
   at RawFileTypePlugin.PixMapReader.DecodePNM()
   at RawFileTypePlugin.RawFileType.GetRAWImageDocument(String file)
   at RawFileTypePlugin.RawFileType.OnLoad(Stream input)
   at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src\Data\FileType.cs:line 498
   at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in D:\src\pdn\src\Fundamentals\Functional\Func.cs:line 58

**Comment by 0xC0000054** [comment]
That error indicates that there is not enough data in the decoded PNM file.

If the RAW file is family-friendly could you zip it and attach it to this issue?
That would allow me to investigate further.

**Comment by SquidingTin** [comment]
[Q1.zip](https://github.com/0xC0000054/pdn-cameraraw/files/10461974/Q1.zip)
here you go

(didnt mean to close)

**Comment by 0xC0000054** [comment]
That file is not a LibRaw supported format, and I am not sure what format it could be. Looking in a hex editor there does not appear to be any file header or footer.

**Comment by SquidingTin** [comment]
odd, ill have to look into this, sorry about bothering you
